services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kaldi
      POSTGRES_PASSWORD: kaldi
      POSTGRES_DB: kaldi
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: